-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
-- 

-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;


SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_webform_custom_panel
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE IF NOT EXISTS `civicrm_webform_custom_panel` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique WebformCustomPanel ID',
     `profile_id` int unsigned    COMMENT 'FK to UF Group',
     `value` text    ,
     `created_date` datetime    COMMENT ' When was the setting created ',
     `created_id` int unsigned    COMMENT 'who created this setting ' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_webform_custom_panel_profile_id FOREIGN KEY (`profile_id`) REFERENCES `civicrm_uf_group`(`id`) ON DELETE CASCADE  
)  ENGINE=InnoDB  ;

 